#========== Spring settings ===========#
#======================================#
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://uat.codingxiaxw.cn:3306/redwood_core
    username: root
    password: fWLjHJEraGPl9T25wxfO
    testSql: SELECT 1
  data:
    mongodb:
      uri: mongodb://taishan.user:CTHoaokA6yQVmQ6lPsFF@172.18.92.169:27017/taishan
  # Redis 连接参数 （RedisProperties）
  redis:
    host: 106.12.28.234
    port: 6379
    ssl: false
    database: 3
    password: laymat@123
    timeout: 2000

